llm:
  api_key: ""
  api_type: "openai"  # 如果 DeepSeek API 兼容 OpenAI 格式，保留；否则改为 "deepseek" 或其他
  model: ""
  base_url: ""


embedding:
  api_type: "openai"
  base_url: ""
  api_key: ""
  model: ""
  dimensions: 1024
  batch_size: 16